// import alphabets from "./alphabets/alphabets"
// import numbers from "./Numbers/numbers"
// import animals from "./Animals/animals"
// import fruits from "./Fruits/fruits"
// import vegetables from "./Vegetables/vegetables"
// import colors from './Colors/colors'
// import shapes from "./Shapes/shapes"
// import vehicles from "./Vehicles/vehicles"
// import bodyParts from "./BodyParts/bodyParts"
// import weather from "./Weather/weather"
// import instruments from "./Instruments/instruments"
// import sports from './Sports/sports'
// import countries from './Countries/countries'
// import professions from "./Professions/professions"
// import foods from "./Food/food"
// import festivals from "./Festivals/festivals"
// import emotions from "./Emotions/emotions"
// import nature from "./Nature/nature"
// import space from "./Space/space"

// const categoryImages = {
     
//     alphabets: [
//         { image: alphabets[0], description: 'A - Apple' },
//         { image: alphabets[1], description: 'B - Ball' },
//         { image: alphabets[2], description: 'C - Cat' },
//         { image: alphabets[3], description: 'D - Dog' },
//         { image: alphabets[4], description: 'E - Elephant' },
//         { image: alphabets[5], description: 'F - Fish' }, 
//         { image: alphabets[6], description: 'G - Goat' },
//         { image: alphabets[7], description: 'H - Horse' },
//         { image: alphabets[8], description: 'I - Ice Cream' },
//         { image: alphabets[9], description: 'J - Joker' },
//         { image: alphabets[10], description: 'K - Kite' },
//         { image: alphabets[11], description: 'L - Lion' },
//         { image: alphabets[12], description: 'M - Monkey' },
//         { image: alphabets[13], description: 'N - Nest' },
//         { image: alphabets[14], description: 'O - Orange' },
//         { image: alphabets[15], description: 'P - Peacock' }, 
//         { image: alphabets[16], description: 'Q - Queen' }, 
//         { image: alphabets[17], description: 'R - Rose' }, 
//         { image: alphabets[18], description: 'S - Sun' }, 
//         { image: alphabets[19], description: 'T - Tiger' }, 
//         { image: alphabets[20], description: 'U - Umbrella' }, 
//         { image: alphabets[21], description: 'V - Van' }, 
//         { image: alphabets[22], description: 'W - Water' }, 
//         { image: alphabets[23], description: 'X - X-mas' }, 
//         { image: alphabets[24], description: 'Y - Yak' }, 
//         { image: alphabets[25], description: 'Z - zebra' }, 

//       ],
       
//       numbers : [
//         { image: numbers[0], description: 'Zero' },
//         { image: numbers[1], description: 'One' },
//         { image: numbers[2], description: 'Two' },
//         { image: numbers[3], description: 'Three' },
//         { image: numbers[4], description: 'Four' },
//         { image: numbers[5], description: 'Five' },
//         { image: numbers[6], description: 'Six' },
//         { image: numbers[7], description: 'Seven' },
//         { image: numbers[8], description: 'Eight' },
//         { image: numbers[9], description: 'Nine' },
//         { image: numbers[10], description: 'Ten' },
//         { image: numbers[11], description: 'Eleven' },
//         { image: numbers[12], description: 'Twelve' },
//         { image: numbers[13], description: 'Thirteen' },
//         { image: numbers[14], description: 'Fourteen' },
//         { image: numbers[15], description: 'Fifteen' },
//         { image: numbers[16], description: 'Sixteen' },
//         { image: numbers[17], description: 'Seventeen' },
//         { image: numbers[18], description: 'Eighteen' },
//         { image: numbers[19], description: 'Nineteen' },
//         { image: numbers[20], description: 'Twenty' },
//       ],
      
//       animals : [
//         { image: alphabets[3], description: 'Dog' },
//         { image: alphabets[4], description: 'Elephant' },
//         { image: alphabets[6], description: 'Goat' },
//         { image: alphabets[7], description: 'Horse' },
//         { image: alphabets[11], description: 'Lion' },
//         { image: alphabets[12], description: 'Monkey' },
//         { image: alphabets[19], description: 'Tiger' }, 
//         { image: alphabets[25], description: 'zebra' }, 
//         { image: animals[0], description: 'Giraffe' }, 
//         { image: animals[1], description: 'Kangaroo' }, 
//         { image: animals[2], description: 'Deer' }, 
//         { image: animals[3], description: 'Dolphin' }, 
//         { image: animals[4], description: 'Koala' }, 
//         { image: animals[5], description: 'Buffalo' }, 
//         { image: animals[6], description: 'Rhinoceros' }, 
//         { image: animals[7], description: 'Cheetah' }, 
//         { image: animals[8], description: 'Panda' }, 
//         { image: animals[9], description: 'Fox' }, 
//         { image: animals[10], description: 'Wolf' }, 
//         { image: animals[11], description: 'Bear' }, 
//         { image: animals[12], description: 'Hippo-potamus' }, 

//       ],

//       fruits :[
//         { image: fruits[0], description: 'Apple' }, 
//         { image: fruits[1], description: 'Banana' }, 
//         { image: fruits[2], description: 'Orange' }, 
//         { image: fruits[3], description: 'Grapes' }, 
//         { image: fruits[4], description: 'Strawberry' }, 
//         { image: fruits[5], description: 'Watermelon' }, 
//         { image: fruits[6], description: 'Pineapple' }, 
//         { image: fruits[7], description: 'Kiwi' }, 
//         { image: fruits[8], description: 'Cherry' }, 
//         { image: fruits[9], description: 'Blueberry' }, 
//         { image: fruits[10], description: 'Mango' }, 
//         { image: fruits[11], description: 'Pear' }, 
//         { image: fruits[12], description: 'Plum' }, 
//         { image: fruits[13], description: 'Raspberry' }, 
//         { image: fruits[14], description: 'Avocado' }, 
//         { image: fruits[15], description: 'Papaya' }, 
//         { image: fruits[16], description: 'Cranberry' }, 
//         { image: fruits[17], description: 'Apricot' }, 
//         { image: fruits[18], description: 'Peach' }, 
//       ],

//       vegetables:[
//         { image: vegetables[0], description: 'Carrot' },
//         { image: vegetables[1], description: 'Potato' },
//         { image: vegetables[2], description: 'Tomato' },
//         { image: vegetables[3], description: 'Broccoli' },
//         { image: vegetables[4], description: 'Spinach' },
//         { image: vegetables[5], description: 'Cucumber' },
//         { image: vegetables[6], description: 'Bell Pepper' },
//         { image: vegetables[7], description: 'Pumpkin' },
//         { image: vegetables[8], description: 'Okra' },
//         { image: vegetables[9], description: 'Peas' },
//         { image: vegetables[10], description: 'Cauliflower' },
//         { image: vegetables[11], description: 'Onion' },
//         { image: vegetables[12], description: 'Garlic' },
//         { image: vegetables[13], description: 'Lettuce' },
//         { image: vegetables[14], description: 'Eggplant' },
//         { image: vegetables[15], description: 'Zucchini' },
//         { image: vegetables[16], description: 'Radish' },
//         { image: vegetables[17], description: 'Green Beans' },
//         { image: vegetables[18], description: 'Asparagus' },
//         { image: vegetables[19], description: 'Celery' },
//         { image: vegetables[20], description: 'Sweet Potato' },
//         { image: vegetables[21], description: 'Bitter Gourd' },
//         { image: vegetables[22], description: 'Cabbage' },
//         { image: vegetables[23], description: 'Mushroom' },
        
//       ],

//       colors : [
//         {image : colors[0], description: 'Red' },
//         {image : colors[1], description: 'Blue' },
//         {image : colors[2], description: 'Green',},
//         {image : colors[3], description: 'Yellow'},
//         {image : colors[4], description: 'Orange' },
//         {image : colors[5], description: 'Purple' },
//         {image : colors[6], description: 'Pink'},
//         {image : colors[7], description: 'Brown' },
//         {image : colors[8], description: 'Black'},
//         {image : colors[9], description: 'White' },
//         {image : colors[10], description: 'Gray' },
//         {image : colors[11], description: 'Turquoise'},
//         {image : colors[12], description: 'Gold' },
//         {image : colors[13], description: 'Silver'},
//         {image : colors[14], description: 'Indigo' },
//         {image : colors[15], description: 'Lavender' },
//         {image : colors[16], description: 'Magenta' },
//         {image : colors[17], description: 'Cyan', },
//         {image : colors[18], description: 'Peach'  },
//         {image : colors[19], description: 'Maroon' }
//     ],

//     shapes:[
//       { image: shapes[0], description: 'Circle' },
//       { image: shapes[1], description: 'Square' },
//       { image: shapes[2], description: 'Triangle' },
//       { image: shapes[3], description: 'Rectangle' },
//       { image: shapes[4], description: 'Oval' },
//       { image: shapes[5], description: 'Heart' },
//       { image: shapes[6], description: 'Star' },
//       { image: shapes[7], description: 'Diamond' },
//       { image: shapes[8], description: 'Pentagon' },
//       { image: shapes[9], description: 'Hexagon' },
//       { image: shapes[10], description: 'Octagon' },
//       { image: shapes[11], description: 'Crescent' },
//       { image: shapes[12], description: 'Arrow' },
//       { image: shapes[13], description: 'Cross' },
//       { image: shapes[14], description: 'Cloud' },
//       { image: shapes[15], description: 'Sun' },
//       { image: shapes[16], description: 'Moon' },
//       { image: shapes[17], description: 'Lightning Bolt' },
//       { image: shapes[18], description: 'Flower' },
//     ],

//     vehicles:[
//       { image: vehicles[0], description: 'Car' },
//       { image: vehicles[1], description: 'Bicycle' },
//       { image: vehicles[2], description: 'Bus' },
//       { image: vehicles[3], description: 'Motorcycle' },
//       { image: vehicles[4], description: 'Train' },
//       { image: vehicles[5], description: 'Helicopter' },
//       { image: vehicles[6], description: 'Truck' },
//       { image: vehicles[7], description: 'Boat' },
//       { image: vehicles[8], description: 'Scooter' },
//       { image: vehicles[9], description: 'Airplane' },
//       { image: vehicles[10], description: 'Ambulance' },
//       { image: vehicles[11], description: 'Fire Truck' },
//       { image: vehicles[12], description: 'Police Car' },
//       { image: vehicles[13], description: 'Tractor' },
//       { image: vehicles[15], description: 'Excavator' },
//       { image: vehicles[17], description: 'Rocket' },
//       { image: vehicles[18], description: 'Cruise Ship' },
//       { image: vehicles[19], description: 'Jet Ski' },
//       { image: vehicles[16], description: 'Hot Air Balloon' },
//       { image: vehicles[14], description: 'Horse Carriage' },
//     ],
    
//     bodyParts: [
//       { image: bodyParts[0], description: 'Head' },
//       { image: bodyParts[1], description: 'Eyes' },
//       { image: bodyParts[2], description: 'Nose' },
//       { image: bodyParts[3], description: 'Mouth' },
//       { image: bodyParts[4], description: 'Ear' },
//       { image: bodyParts[5], description: 'Hair' },
//       { image: bodyParts[6], description: 'Face' },
//       { image: bodyParts[7], description: 'Neck' },
//       { image: bodyParts[8], description: 'Shoulders' },
//       { image: bodyParts[9], description: 'Arms' },
//       { image: bodyParts[10], description: 'Elbows' },
//       { image: bodyParts[11], description: 'Hands' },
//       { image: bodyParts[12], description: 'Fingers' },
//       { image: bodyParts[13], description: 'Chest' },
//       { image: bodyParts[14], description: 'Stomach' },
//       { image: bodyParts[15], description: 'Back' },
//       { image: bodyParts[16], description: 'Waist' },
//       { image: bodyParts[17], description: 'Legs' },
//       { image: bodyParts[18], description: 'Knees' },
//       { image: bodyParts[19], description: 'Feet' },
//       { image: bodyParts[20], description: 'Five Senses' },
//     ],

//     weathers:[
//       { image: weather[0], description: 'Sunny' },
//       { image: weather[1], description: 'Cloudy' },
//       { image: weather[2], description: 'Rainy' },
//       { image: weather[3], description: 'Snowy' },
//       { image: weather[4], description: 'Windy' },
//       { image: weather[5], description: 'Stormy' },
//       { image: weather[6], description: 'Foggy' },
//       { image: weather[7], description: 'Hail' },
//       { image: weather[8], description: 'Rainbow' },
//       { image: weather[9], description: 'Tornado' },
//     ],

//     instruments:[
//       { image: instruments[0], description: 'Piano' },
//       { image: instruments[1], description: 'Guitar' },
//       { image: instruments[2], description: 'Violin' },
//       { image: instruments[3], description: 'Drums' },
//       { image: instruments[4], description: 'Flute' },
//       { image: instruments[5], description: 'Trumpet' },
//       { image: instruments[6], description: 'Saxophone' },
//       { image: instruments[7], description: 'Clarinet' },
//       { image: instruments[8], description: 'Xylophone' },
//       { image: instruments[9], description: 'Tambourine' },
//       { image: instruments[10], description: 'Harp' },
//       { image: instruments[11], description: 'Accordion' },
//       { image: instruments[12], description: 'Banjo' },
//       { image: instruments[13], description: 'Harmonica' },
//       { image: instruments[14], description: 'Cello' },
//       { image: instruments[15], description: 'Bagpipes' },
//       { image: instruments[16], description: 'Oboe' },
//       { image: instruments[17], description: 'Mandolin' },
//       { image: instruments[18], description: 'Ukulele' },
//       { image: instruments[19], description: 'Maracas' },
//     ],

//     sports:[
//       { image: sports[0], description: 'Soccer' },
//       { image: sports[1], description: 'Basketball' },
//       { image: sports[2], description: 'Tennis' },
//       { image: sports[3], description: 'Cricket' },
//       { image: sports[4], description: 'Baseball' },
//       { image: sports[5], description: 'Golf' },
//       { image: sports[6], description: 'Swimming' },
//       { image: sports[7], description: 'Running' },
//       { image: sports[8], description: 'Table Tennis' },
//       { image: sports[9], description: 'Volleyball' },
//       { image: sports[10], description: 'Rugby' },
//       { image: sports[11], description: 'Badminton' },
//       { image: sports[12], description: 'Ice Hockey' },
//       { image: sports[13], description: 'Boxing' },
//       { image: sports[14], description: 'Martial Arts' },
//       { image: sports[15], description: 'Cycling' },
//       { image: sports[16], description: 'Skiing' },
//       { image: sports[17], description: 'Gymnastics' },
//       { image: sports[18], description: 'Wrestling' },
//       { image: sports[19], description: 'Snow-   boarding' },
//     ],

//     countries:[
//       { image: countries[10], description: 'India' },
//       { image: countries[0], description: 'United States' },
//       { image: countries[3], description: 'Australia' },
//       { image: countries[2], description: 'Canada' },
//       { image: countries[1], description: 'United Kingdom' },
//       { image: countries[4], description: 'Germany' },
//       { image: countries[5], description: 'France' },
//       { image: countries[6], description: 'Italy' },
//       { image: countries[7], description: 'Spain' },
//       { image: countries[8], description: 'Japan' },
//       { image: countries[9], description: 'China' },
//       { image: countries[11], description: 'Brazil' },
//       { image: countries[12], description: 'Argentina' },
//       { image: countries[13], description: 'Mexico' },
//       { image: countries[14], description: 'Russia' },
//       { image: countries[15], description: 'South Africa' },
//       { image: countries[16], description: 'Egypt' },
//       { image: countries[17], description: 'Turkey' },
//       { image: countries[18], description: 'South Korea' },
//       { image: countries[19], description: 'Netherlands' },
//       { image: countries[20], description: 'Switzerland' },
//       { image: countries[21], description: 'New Zealand' },
//       { image: countries[22], description: 'Sri Lanka' },
//       { image: countries[23], description: 'Pakistan' },
//       { image: countries[24], description: 'Afghanistan' },

//     ],
//     professions : [
//       { image: professions[0], description: 'Doctor' },
//       { image: professions[1], description: 'Engineer' },
//       { image: professions[2], description: 'Teacher' },
//       { image: professions[3], description: 'Lawyer' },
//       { image: professions[4], description: 'Chef' },
//       { image: professions[5], description: 'Firefighter' },
//       { image: professions[6], description: 'Police Officer' },
//       { image: professions[7], description: 'Pilot' },
//       { image: professions[8], description: 'Astronaut' },
//       { image: professions[9], description: 'Artist' },
//       { image: professions[10], description: 'Musician' },
//       { image: professions[11], description: 'Actor' },
//       { image: professions[12], description: 'Athlete' },
//       { image: professions[13], description: 'Scientist' },
//       { image: professions[14], description: 'Architect' },
//       { image: professions[15], description: 'Writer' },
//       { image: professions[16], description: 'Nurse' },
//       { image: professions[17], description: 'Farmer' },
//       { image: professions[18], description: 'Photographer' },
//       { image: professions[19], description: 'Veterinarian' },
//       { image: professions[20], description: 'Electrician' },
//       { image: professions[21], description: 'Plumber' },
//       { image: professions[22], description: 'Carpenter' },
//       { image: professions[23], description: 'Hairdresser' },
    
//     ],
//     foods: [
//       { image: foods[0], description: 'Cake' },
//       { image: foods[1], description: 'Candy' },
//       { image: foods[2], description: 'Egg' },
//       { image: foods[3], description: 'Cheese' },
//       { image: foods[4], description: 'Milk' },
//       { image: foods[5], description: 'Bread' },
//       { image: foods[6], description: 'Butter' },
//       { image: foods[7], description: 'Jelly' },
//       { image: foods[8], description: 'Pizza' },
//       { image: foods[9], description: 'Ice Cream' },
//       { image: foods[10], description: 'Chocolate' },
//       { image: foods[11], description: 'Peanut Butter' },
//       { image: foods[12], description: 'Popcorn' },
//       { image: foods[13], description: 'Yogurt' },
//       { image: foods[14], description: 'Pancake' },
//       { image: foods[15], description: 'French Fries' },
//       { image: foods[16], description: 'Spaghetti' },
//       { image: foods[17], description: 'Hamburger' },
//       { image: foods[18], description: 'Sushi' },
//       { image: foods[19], description: 'Muffin' },
//     ],

//     festivals:[
//         { image: festivals[0], description: 'Independence Day'},
//         { image: festivals[1], description: 'Diwali'},
//         { image: festivals[2], description: 'Raksha Bandhan'},
//         { image: festivals[3], description: 'Durga Puja'},
//         { image: festivals[4], description: 'Dussehra'},
//         { image: festivals[5], description: 'Christmas'},
//         { image: festivals[6], description: 'Onam'},
//         { image: festivals[7], description: 'Pongal'},
//         { image: festivals[8], description: 'Bakrid'},
//         { image: festivals[9], description: 'Holi'},
//         { image: festivals[10], description: 'Ganeshotsav'},
//         { image: festivals[11], description: 'Ugadi'},
//         { image: festivals[12], description: 'Maha Shivaratri'},
//         { image: festivals[13], description: 'Ramazan'},
//     ],
    
//     emotions: [
//       { image: emotions[0], description: 'Joy' },
//       { image: emotions[1], description: 'Sadness' },
//       { image: emotions[2], description: 'Anger' },
//       { image: emotions[3], description: 'Fear' },
//       { image: emotions[4], description: 'Surprise' },
//       { image: emotions[5], description: 'Disgust' },
//       { image: emotions[6], description: 'Love' },
//       { image: emotions[7], description: 'Excitement' },
//       { image: emotions[8], description: 'Contentment' },
//       { image: emotions[9], description: 'Boredom' },
//       { image: emotions[10], description:'Curiosity'  },
//       { image: emotions[11], description:'Confusion'  },
//       { image: emotions[12], description:'Disappointment'  },
//       { image: emotions[13], description:'Frustration'  },
//       { image: emotions[14], description:'Envy'  },
//       { image: emotions[15], description:'Guilt'  },
//       { image: emotions[16], description:'Shame'  },
//       { image: emotions[17], description:'Amusement'  },
//     ],
    
//     nature:[
//       {image: nature[0], description: 'Mountain'},
//       {image: nature[1], description: 'Lake'},
//       {image: nature[2], description: 'Forest'},
//       {image: nature[3], description: 'Ocean'},
//       {image: nature[4], description: 'River'},
//       {image: nature[5], description: 'Waterfalls'},
//       {image: nature[6], description: 'Sunset'},
//       {image: nature[7], description: 'Landscape'},
//       {image: nature[8], description: 'Wildlife'},
//       {image: nature[9], description: 'Flowers'},
//       {image: nature[10], description: 'Deserts'},
//       {image: nature[11], description: 'Clouds'},
//       {image: nature[12], description: 'Beach'},
//       {image: nature[13], description: 'Island'},
//       {image: nature[14], description: 'Skies'},
//       {image: nature[15], description: 'Field'},
//       {image: nature[16], description: 'Season'},
//       {image: nature[17], description: 'Sunrise'},
//       {image: nature[18], description: 'Underwater'},
//       {image: nature[19], description: 'Countryside'},
//     ],
//     space:[
//       {image: space[0], description: 'Planets'},
//       {image: space[1], description: 'Stars'},
//       {image: space[2], description: 'Galaxy'},
//       {image: space[3], description: 'Nebula'},
//       {image: space[4], description: 'Black Hole'},
//       {image: space[5], description: 'Moon'},
//       {image: space[6], description: 'Astronaut'},
//       {image: space[7], description: 'Spacecraft'},
//       {image: space[8], description: 'Telescope'},
//       {image: space[9], description: 'Satellite'},
//       {image: space[10], description: 'Meteoroids'},
//       {image: space[11], description: 'Comet'},
//       {image: space[12], description: 'Constellations'},
//       {image: space[13], description: 'Space Exploration'},
//       {image: space[14], description: 'Space Shuttle'},
//       {image: space[15], description: 'Space Station'},
//       {image: space[16], description: 'Solar System'},
//       {image: space[18], description: 'Cosmic Event'},
//       {image: space[19], description: 'Celestial Bodies'}
//     ]
    

// }

// export default categoryImages